### ISSUE TITLE
Fix System.tar.gz availability

### ISSUE THREAD

**Issue by Lrs121** [AsteroidOS/meta-sparrow-hybris#2]
Migrated to a new server operating system and I'm still working out the bugs with the web portion. This includes the path to the system.tar.gz file needed to build AsteroidOS.

I might try a Dropbox mirror but I don't​ know what bandwidth restrictions they have.

This is a high priority however the end of the semester is nearly upon me and my time is limited. Once I graduate, I should have more time to work on this.

**Comment by FlorentRevest** [comment]
Hi Larson,
Good luck with the end of your semester!
All the other system tarballs are hosted on my dropbox account, you can
send me the tarball by email and I'll change your layer.

2017-04-11 18:15 GMT+02:00 Larson T. <notifications@github.com>:

**Comment by Lrs121** [comment]
Hello Florent,
Sounds good to me, I'll try and get that sent as soon as possible.
