### ISSUE TITLE
No bluetooth on reboots.

### ISSUE THREAD

**Issue by marcdw1289** [AsteroidOS/meta-sparrow-hybris#4]
On my ASUS Zenwatch 2 sparrow I noticed something. I still have Wear OS on the watch so I'm dual booting. If I fastboot boot AsteroidOS I have Bluetooth. When I boot via the TWRP method (boot image backed up and restored when I need it) Bluetooth is off and can't be turned on via Settings. The BT icon in the quick settings can be toggled on/off but it doesn't do anything.
Is this a known issue? I'm not sure what to do next to troubleshoot the issue.

**Comment by FlorentRevest** [comment]
Thank you for reporting :) this issue hadn't been brought up before.
Could you maybe get logs from "dmesg", "journalctl --no-pager" and "hciconfig" when you boot AsteroidOS from TWRP ? This sounds hard to debug/explain though...

**Comment by marcdw1289** [comment]
Sorry for late reply, and thanks.
I assume the commands are to be entered via adb shell? When AsteroidOS is running it is completely invisible to the computer. Tried all the USB but got nothing. All good while in WearOS or TWRP.
Anyhind, after numerous reboots (while figuring out the USB situation) the Bluetooth eventually turned on. AsteroidOS Sync saw and paired the watch but would disconnect after a second. That was a one-off thing. Several reboots later I'm back to no BT.
Haven't given up though. :-)

**Comment by mauricioduarte01** [comment]
Hello, I am having the same issue when dualbooting my sparrow. The watch is unusable because is impossible to connect to my phone via BT. AsteroidOS sync nor Telescope for UT works for sync, both can find the device but fails when trying to pair.
Thank you for the effort.

**Comment by marcdw1289** [comment]
Many many apologies for not getting back to this issue. Since my original post I decided to dedicate the watch to just AsteroidOS. WearOS has been removed but TWRP is still present.
The issue/behavior is the same. After initial fastboot boot of the OS the Bluetooth works. I tried to keep it up for a few days but battery drain is quite high so it didn't make it through an 8-hour work shift. That's when I realized that just rebooting in general gives me no Bluetooth. Reboot after reboot, shutdown and restarts, no BT. Hook it up to a PC and fastboot boot it, then it works.

I have free time so I'll gather up the info Florent asked me for. Sorry for that also.

**Comment by marcdw1289** [comment]
Okay @FlorentRevest , I finally got the output you requested. Again, my deepest apologies for such a belated post.
I downloaded and installed the latest builds first.
I have both the output when BT is working (On) and not (Off).

Bluetooth working after initial fastboot boot...
[dmesg_BTon.txt](https://github.com/AsteroidOS/meta-sparrow-hybris/files/4261512/dmesg_BTon.txt)

[hciconfig_BTon.txt](https://github.com/AsteroidOS/meta-sparrow-hybris/files/4261514/hciconfig_BTon.txt)

[journalctl_BTon.txt](https://github.com/AsteroidOS/meta-sparrow-hybris/files/4261518/journalctl_BTon.txt)

Bluetooth not working on reboots/restarts. Note that hciconfig returns nothing...
[dmesg_BToff.txt](https://github.com/AsteroidOS/meta-sparrow-hybris/files/4261529/dmesg_BToff.txt)

[journalctl_BToff.txt](https://github.com/AsteroidOS/meta-sparrow-hybris/files/4261530/journalctl_BToff.txt)

**Comment by qu4nd** [comment]
That's no dual boot issue. Same happend on my real installation.

**Comment by marcdw1289** [comment]
@qu4nd , yep. I mentioned that I now just have AsteroidOS on the watch with same results. Maybe I should change the title.

**Comment by marcdw1289** [comment]
Been away from my watch for awhile. Not much use for it while sitting at home.
Anyway, just checked things out. The Bluetooth is working out just fine. Several reboots throughout the day, reconnects without issue.
Kudos to the devs.
